package com.github.zoltar238.PrintStainServer.dto;

public enum ResponsesEnum {OK, EMAIL_ALREADY_REGISTERED, USERNAME_ALREADY_REGISTERED, LOGIN_ERROR, LOGIN_CORRECT, IMAGE_PROCESS_ERROR, SALE_ITEM_NOT_FOUND, BAD_REQUEST, CREATED, UNEXPECTED_ERROR}
